apiVersion: apps/v1
kind: Deployment
metadata:
  name: acopio-deployment
  labels:
    app: acopio-deployment
spec:
  selector:
    matchLabels:
      app: acopio-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: acopio-deployment
    spec:
      containers:
        - name: acopio
          image: marcelovargaspavez/acopio
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
