apiVersion: apps/v1
kind: Deployment
metadata:
  name: pago-deployment
  labels:
    app: pago-deployment
spec:
  selector:
    matchLabels:
      app: pago-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: pago-deployment
    spec:
      containers:
        - name: pago
          image: marcelovargaspavez/pago
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: pago-service
  labels:
    app: pago-service
spec:
  selector:
    app: pago-deployment
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer