apiVersion: v1
kind: Service
metadata:
  name: propiedades-service
  labels:
    app: propiedades-service
spec:
  selector:
    app: propiedades-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer